name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: espjs
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image latest
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: |
          linux/arm/v6
          linux/arm/v7
          linux/amd64
          linux/arm64/v8
        push: true
        tags: espjs/home:latest

    - name: Build and push Docker image dev
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: |
          linux/arm/v6
          linux/arm/v7
          linux/amd64
          linux/arm64/v8
        file: DockerfileDev
        push: true
        tags: espjs/home:dev
